mod expand_restriction_fragments;
pub use expand_restriction_fragments::ExpandRestrictionFragments;
mod expand_extension_fragments;
pub use expand_extension_fragments::ExpandExtensionFragments;
mod flatten_nested_groups;
pub use flatten_nested_groups::{FlattenNestedChoices, FlattenNestedSequences};
mod expand_short_form_complex_types;
pub use expand_short_form_complex_types::ExpandShortFormComplexTypes;
mod expand_groups;
pub use expand_groups::ExpandGroups;
mod expand_attribute_declarations;
pub use expand_attribute_declarations::ExpandAttributeDeclarations;
mod remove_prohibited_attributes;
pub use remove_prohibited_attributes::RemoveProhibitedAttributes;
mod single_choice_to_sequence;
pub use single_choice_to_sequence::SingleChoiceToSequence;
