[workspace]
resolver = "2"
members = ["xsd", "xsd-codegen-xmlity", "xsd-type-compiler", "xmlity-build"]

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.82.0"
authors = ["Lukas Friman <lukas@dreamplay.net>"]
repository = "https://github.com/lukasfri/xsd-toolkit"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
thiserror = "^2.0.4"
pretty_assertions = "^1.4.1"
rstest = "^0.25.0"
xmlity = { version = "0.0.5", features = [
  "derive",
], git = "https://github.com/lukasfri/xmlity.git", rev = "c2d2e7d63eaa1f45b250d4cff6508f7faa568543" }
xmlity-quick-xml = { version = "0.0.5", git = "https://github.com/lukasfri/xmlity.git", rev = "c2d2e7d63eaa1f45b250d4cff6508f7faa568543" }
