[workspace]
resolver = "2"
members = [
  "xsd",
  "xsd-codegen-xmlity",
  "xsd-fragments",
  "xmlity-build",
  "schemas/xmlity-ns",
  "schemas/xmlity-ns-xs",
  "schemas/xmlity-ns-xsi",
  "schemas/xmlity-ns-xml",
  "schemas/xbrl-xsd",
  "xsd-dynamic-query",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.82.0"
authors = ["Lukas Friman <lukas@dreamplay.net>"]
homepage = "https://github.com/lukasfri/xsd-toolkit"
documentation = "https://docs.rs/xsd"
repository = "https://github.com/lukasfri/xsd-toolkit"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
xmlity-ns-xs = { path = "schemas/xmlity-ns-xs" }
xmlity-ns-xsi = { path = "schemas/xmlity-ns-xsi" }
xmlity-ns-xml = { path = "schemas/xmlity-ns-xml" }
xmlity-ns = { path = "schemas/xmlity-ns" }
xmlity-build = { path = "xmlity-build" }
xbrl-xsd = { path = "schemas/xbrl-xsd" }
thiserror = "^2.0.4"
pretty_assertions = "^1.4.1"
rstest = "^0.25.0"
ntest = "0.9.3"
xmlity = { version = "0.0.8", features = [
  "derive",
], git = "https://github.com/lukasfri/xmlity.git", rev = "c6cdccc611e063eb7bd9f46033dc44abe4e9ad08" }
xmlity-quick-xml = { version = "0.0.8", git = "https://github.com/lukasfri/xmlity.git", rev = "c6cdccc611e063eb7bd9f46033dc44abe4e9ad08" }
url = { version = "2.5.4" }
derive_more = { version = "2.0.1", features = ["full"] }
static_assertions = "1.1.0"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
unwrap_used = "warn"
