[package]
name = "xmlity-ns-xsd-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
xmlity = { workspace = true }
xsd-types = "0.9.6"
derive_more.workspace = true
xsd-codegen-xmlity = { path = "../../xsd-codegen-xmlity" }
syn = "2.0"

[lints]
workspace = true
