[package]
name = "xsd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
xmlity.workspace = true
xmlity-quick-xml.workspace = true
derive_more.workspace = true
xmlity-ns-xs.workspace = true
xmlity-ns.workspace = true
thiserror.workspace = true
glob = "0.3.2"
futures = "0.3.31"
url.workspace = true

[dev-dependencies]
rstest.workspace = true
pretty_assertions.workspace = true
ntest.workspace = true


[lints]
workspace = true
